### ISSUE TITLE
would like to use .jsonc as commented json input file and .json as stripped automatic output

### ISSUE THREAD

**Issue by bcowgill** [sindresorhus/strip-json-comments-cli#1]
something like 

strip-json-comments-cli *.jsonc

and it would write a .json for every .jsonc provided.
using glob as well it could be quite useful.

**Comment by bcowgill** [comment]
Found an alternative.
http://json5.org/
 json5 -c path/to/foo.json5    # generates path/to/foo.json

**Comment by kevva** [comment]
Yeah, this is probably not in the scope for this module. The CLI aims to be simple and just write to `stdout`.
