### ISSUE TITLE
3.0.0 won't work on macbook intel, please help.

### ISSUE THREAD

**Issue by JCDenton47** [sindresorhus/strip-json-comments-cli#6]
file:///Users/.nvm/versions/node/v14.20.1/lib/node_modules/strip-json-comments-cli/node_modules/meow/build/index.js:29
	description &&= help ? `\n  ${description}\n` : `\n${description}`;
	            ^^^

SyntaxError: Unexpected token '&&='
    at Loader.moduleStrategy (internal/modules/esm/translators.js:145:18)

**Comment by sindresorhus** [comment]
Update your Node.js version.
